# Generated by Django 5.2.11 on 2026-02-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="training",
            options={
                "ordering": ["-start_date", "-published_at", "-created_at", "-id"]
            },
        ),
        migrations.AlterModelOptions(
            name="trainingregistration",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.RemoveIndex(
            model_name="trainingregistration",
            name="training_tr_trainin_951a44_idx",
        ),
        migrations.RemoveIndex(
            model_name="trainingregistration",
            name="training_tr_status_3151e1_idx",
        ),
        migrations.RemoveField(
            model_name="training",
            name="price_currency",
        ),
        migrations.AlterUniqueTogether(
            name="trainingregistration",
            unique_together={("training", "email")},
        ),
        migrations.AddField(
            model_name="training",
            name="currency",
            field=models.CharField(default="GBP", max_length=10),
        ),
        migrations.AddField(
            model_name="training",
            name="duration_label",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="training",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="training",
            name="slug",
            field=models.SlugField(blank=True, max_length=240, unique=True),
        ),
        migrations.AddField(
            model_name="training",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="training",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="trainingregistration",
            name="organisation",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="trainingregistration",
            name="payment_status",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="training",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="training",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="training",
            name="price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="training",
            name="title",
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name="trainingregistration",
            name="full_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="trainingregistration",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="trainingregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="trainingregistration",
            name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="trainingregistration",
            name="paid_currency",
        ),
    ]
