# Generated by Django 5.2.11 on 2026-02-25 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lead_type",
                    models.CharField(
                        choices=[
                            ("contact", "Contact enquiry"),
                            ("newsletter", "Newsletter subscription"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In progress"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField(blank=True)),
                ("marketing_consent", models.BooleanField(default=False)),
                ("source_path", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.RemoveField(
            model_name="contactlead",
            name="handled_by",
        ),
        migrations.DeleteModel(
            name="NewsletterSubscriber",
        ),
        migrations.DeleteModel(
            name="ContactLead",
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["lead_type", "status", "created_at"],
                name="leads_lead_lead_ty_0a0ee1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="leads_lead_email_f663dc_idx"),
        ),
    ]
